name: StoneRecipes
main: shadows.stonerecipes.StoneRecipes
version: 4.1.2
author: Shadows_of_Fire
api-version: 1.16
depend: [ProtocolLib, helper, StoneBlock]
commands:
  giveitem:
    usage: /giveitem <player> <item id> <amount>
    permission: stone.give
  srbackup:
    usage: May only be run from console.
    permission: sr.backup