name: StoneRecipes
main: shadows.stonerecipes.StoneRecipes
version: 3.0.0
author: Shadows_of_Fire
api-version: 1.14
commands:
  giveitem:
    usage: /giveitem <player> <item id> <amount>
    permission: stone.give
  srbackup:
    usage: May only be run from console.
    permission: sr.backup